INSERT INTO MY_CLIENT(ID, NAME, EMAIL, FAVORITERECIPEIDLIST) VALUES(1, 'client1', 'client1@client.com', ARRAY[1,2,3]);
INSERT INTO MY_CLIENT(ID, NAME, EMAIL, FAVORITERECIPEIDLIST) VALUES(2, 'client2', 'client2@client.com', ARRAY[5,10,15]);
INSERT INTO MY_CLIENT(ID, NAME, EMAIL, FAVORITERECIPEIDLIST) VALUES(3, 'client3', 'client3@client.com', ARRAY[20,40,45, 50]);
ALTER SEQUENCE MY_CLIENT_seq RESTART WITH 4;
